# Generated by Django 4.2.1 on 2023-05-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品名称', 'verbose_name_plural': '产品管理'},
        ),
    ]
