# Generated by Django 4.2.1 on 2023-05-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_alter_apitest_options_remove_apitest_apitestdesc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitest',
            options={'verbose_name': '流程场景接口', 'verbose_name_plural': '流程场景接口'},
        ),
    ]
